# Generated by Django 4.2.3 on 2023-07-06 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_alter_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='https://dribbble.com/shots/4187820-404-Food-Not-Found', max_length=500, upload_to=''),
        ),
    ]
