# Generated by Django 4.2.3 on 2023-07-14 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_rename_price_item_time_item_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='link',
            field=models.CharField(default='', max_length=500),
        ),
    ]
