# Generated by Django 4.2.3 on 2023-07-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0010_item_clicked'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.CharField(blank=True, choices=[('Breakfast', 'Breakfast'), ('Dinner', 'Dinner'), ('Easy', 'Easy'), ('Medium', 'Medium'), ('Difficult', 'Difficult'), ('Meaty', 'Meaty'), ('Healthy', 'Healthy')], max_length=50),
        ),
    ]
