# Generated by Django 4.2.3 on 2023-07-18 17:22

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0014_tag_remove_item_tags_item_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='item',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Breakfast', 'Breakfast'), ('Dinner', 'Dinner'), ('Easy', 'Easy'), ('Medium', 'Medium'), ('Difficult', 'Difficult'), ('Meaty', 'Meaty'), ('Healthy', 'Healthy'), ('Pizza', 'Pizza'), ('Vegetables', 'Vegetables'), ('Pie', 'Pie'), ('Dessert', 'Dessert'), ('Vegan', 'Vegan')], max_length=50),
        ),
    ]
