# Generated by Django 4.2.3 on 2023-07-18 17:25

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0015_remove_item_tags_delete_tag_item_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Very easy', 'Very easy'), ('Easy', 'Easy'), ('Medium', 'Medium'), ('Difficult', 'Difficult'), ('Breakfast', 'Breakfast'), ('Dinner', 'Dinner'), ('Meaty', 'Meaty'), ('Healthy', 'Healthy'), ('Pizza', 'Pizza'), ('Vegetables', 'Vegetables'), ('Pie', 'Pie'), ('Dessert', 'Dessert'), ('Vegan', 'Vegan')], max_length=50),
        ),
    ]
